name: Build Artifacts

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Clone Mindustry
      run: |
        git clone --depth=1 --branch=me-things https://github.com/Blockzilla101/Mindustry
    - name: Set env
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        hashes=$(find ./Mindustry/core/assets-raw/sprites -type f | xargs sha256sum | sha256sum)
        echo "spriteHashes=${hashes:0:(-3)}" >> $GITHUB_ENV
    - name: Cache Generated Sprites
      uses: actions/cache@v2
      with:
        path: |
          ./Mindustry/core/assets/sprites
          ./Mindustry/core/assets-raw/sprites_out
        key: sprites-${{ env.spriteHashes }}
    - name: Create artifacts
      run: |
        cd ./Mindustry
        MindustryBE=$(curl --silent "https://api.github.com/repos/Anuken/MindustryBuilds/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
        ./gradlew desktop:dist server:dist -PantigriefVersion=${RELEASE_VERSION} -Pbuildversion=${MindustryBE} -PversionType=bleeding-edge --stacktrace
        mv desktop/build/libs/Mindustry.jar desktop/build/libs/Mindustry-Antigrief-BE-Desktop-${RELEASE_VERSION}.jar
        mv server/build/libs/server-release.jar server/build/libs/Mindustry-Antigrief-BE-Server-${RELEASE_VERSION}.jar
        cd ../
    - name: Upload BE desktop artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Mindustry/desktop/build/libs/Mindustry-Antigrief-BE-Desktop-${{ env.RELEASE_VERSION }}.jar
        tag: ${{ github.ref }}
    - name: Upload BE server artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Mindustry/server/build/libs/Mindustry-Antigrief-BE-Server-${{ env.RELEASE_VERSION }}.jar
        tag: ${{ github.ref }}
